/**
 * AGOL Popup Studio — HTML Import Parser
 * Parses popup HTML previously generated by this tool back into editor state.
 * Uses the browser's built-in DOMParser so no dependencies are needed.
 */

function extractColorFromBorder(borderStr) {
  if (!borderStr) return '';
  const match = borderStr.match(/#[0-9a-fA-F]{3,8}|rgba?\([^)]+\)/);
  return match ? match[0] : '';
}

export function parseStudioHtml(rawHtml) {
  const hasMarker = rawHtml.includes('<!-- AGOL_POPUP_STUDIO -->');

  // Strip the marker comment before parsing so DOMParser doesn't choke
  const html = rawHtml.replace('<!-- AGOL_POPUP_STUDIO -->', '').trim();

  const parser = new DOMParser();
  const doc = parser.parseFromString(`<body>${html}</body>`, 'text/html');

  const colors = {};
  let popupFont = 'Microsoft YaHei, sans-serif';
  let popupAlign = 'center';
  let popupHeader = '{nickname}';
  const fieldOrder = [];
  const fieldAliases = {};
  const urlFieldHints = [];
  const urlButtonTexts = {};

  // ---- Parse header <div> ----
  const headerDiv = doc.querySelector('body > div');
  if (headerDiv) {
    const s = headerDiv.style;
    colors.header_bg = s.background || s.backgroundColor || '';
    colors.header_text = s.color || '';
    // `border` shorthand e.g. "2px solid #ffffff"
    colors.header_border = extractColorFromBorder(s.border || s.borderBottom || '');
    if (s.fontFamily) popupFont = s.fontFamily;
    if (s.textAlign) popupAlign = s.textAlign;
    popupHeader = headerDiv.textContent.trim();
  }

  // ---- Parse <table> for outline color ----
  const table = doc.querySelector('table');
  if (table) {
    const s = table.style;
    colors.table_outline = extractColorFromBorder(s.border || '');
    // Confirm font from table if header didn't have it
    if (!colors.header_bg && s.fontFamily) popupFont = s.fontFamily;
  }

  // ---- Parse each <tr> row ----
  let firstDataRow = true;
  doc.querySelectorAll('tbody tr').forEach(row => {
    const tds = row.querySelectorAll('td');
    if (tds.length < 2) return;

    const leftTd = tds[0];
    const rightTd = tds[1];

    // Pull row-level colors from the first real data row
    if (firstDataRow) {
      firstDataRow = false;
      colors.row_label_bg = leftTd.style.background || leftTd.style.backgroundColor || '';
      colors.row_label_text = leftTd.style.color || '';
      colors.row_value_bg = rightTd.style.background || rightTd.style.backgroundColor || '';
      colors.row_value_text = rightTd.style.color || '';
      colors.table_border = extractColorFromBorder(leftTd.style.borderBottom || '');
    }

    const alias = leftTd.textContent.trim();
    const anchor = rightTd.querySelector('a');
    let fieldName = null;

    if (anchor) {
      // URL field — extract name from href token: {expression/url_fieldname}
      const href = anchor.getAttribute('href') || '';
      const urlMatch = href.match(/\{expression\/url_([^}]+)\}/);
      fieldName = urlMatch ? urlMatch[1] : alias.toLowerCase().replace(/\s+/g, '_');

      urlFieldHints.push(fieldName);
      urlButtonTexts[fieldName] = anchor.textContent.trim();

      // Button colors and styles
      const as = anchor.style;
      colors.button_bg = as.background || as.backgroundColor || '';
      colors.button_text = as.color || '';
      colors.button_radius = as.borderRadius || '4px';
      colors.button_shadow = as.boxShadow || 'none';
    } else {
      const content = rightTd.textContent.trim();

      // {field_name} → direct field reference
      const directMatch = content.match(/^\{([^/}]+)\}$/);
      // {expression/fmt_fieldname} → date-formatted Arcade expression
      const exprMatch = content.match(/^\{expression\/fmt_([^}]+)\}$/);

      if (directMatch) {
        fieldName = directMatch[1];
      } else if (exprMatch) {
        fieldName = exprMatch[1];
      } else {
        // Fallback: derive a safe field name from the alias
        fieldName = alias.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '');
      }
    }

    if (fieldName && !fieldOrder.includes(fieldName)) {
      fieldOrder.push(fieldName);
      fieldAliases[fieldName] = alias;
    }
  });

  return {
    hasMarker,
    colors,
    fieldOrder,
    fieldAliases,
    urlFieldHints,
    urlButtonTexts,
    popupHeader,
    popupAlign,
    popupFont,
  };
}
